name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        env: 
          GITHUB_TOKEN: ${{ github.token }}
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/afanasievkirill/telegram-swear-bot/leshin-bot
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"